name: droNET
channels:
  - conda-forge
  - cogsci
  - defaults
dependencies:
  - python=3.10.8
  - pip=22.3.1
  - tensorflow=2.10.0
  - keras=2.10.0
  - numpy=1.23.5
  - pandas=1.5.2
  - matplotlib=3.6.2
  - seaborn=0.12.1
  - scipy=1.9.3
  - pygame=2.1.3
  - tqdm=4.64.1